### ISSUE TITLE
UI/UX feedback

### ISSUE THREAD

**Issue by gsong** [tabbykatz/game-night#27]
- Combine "Home" and "Dashboard" based on `isAuthenticated` state.
- Fill out nav when authenticated with links to my games and my events.

## Dashbaord

- Strike the word "Your" from most headers.
- Consider a frame around the two sections to make them distinctive:
  - Games
  - Events
- If there are no recently added games or upcoming events, consider helper text that guides the user on what to do.
- "Add more games to your collection," "See your entire game collection." No need to be stingy with link labels.

## Add Games

- Enlarget the input and the buttons. Input text needs to be at least 16px in order for iOS to not zoom into the input field.
- If there are no search results, say so.
- If you set the wrapper `<div>`s in your `<li>`s to 100% height, then you won't have the problem of cards not fitting.
- Add some padding to the cards so there's breathing room for the content.
- I would opt for larger cards personally.
- The + / - controls can be full on buttons with words, e.g. "Add to collection," "Remove from collection."

## Game Detail

- Does the description need to be hidden behind a disclosure?
- Maybe have the header span the whole area, across both image and details?
- The details should perhaps stack below the image at certain viewport size.
- The description can go with the rest of the detail. Constrain its width to something like 70ch.

## Create Event

- Instead of nice-dates, why not use `<input type="datetime-local">`?
- Address is a [`fieldset`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset), still label each field.
- Label the dates.
- The description area can be much larger.
- Event name is probably just a text iput, not a text area.

## Event List

- Maybe a bit more info on the cards? Like start date? How many people?

## Event Detail

- If a user doesn't exist, it's not because it's "Not a valid user email."
- "Edit Event" and "Delete Event" probably shouldn't have the same weight as "Add attendee." Perhaps move those controls closer to the event title?

## Add game to event

- When navigating back to the event, I briefly get a 404.

**Comment by tabbykatz** [comment]
> Consider a frame around the two sections to make them distinctive:
Games
Events

What would this look like? Do you mean in the dashboard?

**Comment by tabbykatz** [comment]
-  [x] Combine "Home" and "Dashboard" based on `isAuthenticated` state.
-  [x] Fill out nav when authenticated with links to my games and my events.

## Dashboard
-  [x] Strike the word "Your" from most headers.
-  [ ] Consider a frame around the two sections to make them distinctive:
   * Games
   * Events
 -  [ ] * If there are no recently added games or upcoming events, consider helper text that guides the user on what to do.
-  [x] "Add more games to your collection," "See your entire game collection." No need to be stingy with link labels.

 ## Add Games
-  [x] Enlarge the input and the buttons. Input text needs to be at least 16px in order for iOS to not zoom into the input field.
-  [ ] * If there are no search results, say so.
-  [ ] * If you set the wrapper `<div>`s in your `<li>`s to 100% height, then you won't have the problem of cards not fitting.
-  [ ] * Add some padding to the cards so there's breathing room for the content.
-  [ ]  * I would opt for larger cards personally.
-  [ ]  * The + / - controls can be full on buttons with words, e.g. "Add to collection," "Remove from collection."

 ## Game Detail
-  [ ]  * Does the description need to be hidden behind a disclosure?
-  [ ]  * Maybe have the header span the whole area, across both image and details?
-  [ ]  * The details should perhaps stack below the image at certain viewport size.
-  [ ]  * The description can go with the rest of the detail. Constrain its width to something like 70ch.

 ## Create Event
-  [ ] * Instead of nice-dates, why not use `<input type="datetime-local">`?
-  [ ]  * Address is a [`fieldset`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset), still label each field.
-  [ ]  * Label the dates.
-  [ ]  * The description area can be much larger.
-  [ ]  * Event name is probably just a text iput, not a text area.

 ## Event List
-  [ ]  * Maybe a bit more info on the cards? Like start date? How many people?
 
 ## Event Detail
-  [ ]  * If a user doesn't exist, it's not because it's "Not a valid user email."
-  [ ]  * "Edit Event" and "Delete Event" probably shouldn't have the same weight as "Add attendee." Perhaps move those controls closer to the event title?

 ## Add game to event
-  [ ]  * When navigating back to the event, I briefly get a 404.
